import { cronJobs } from "convex/server";
// @ts-ignore - api will be generated by Convex
import { api } from "./_generated/api";

const crons = cronJobs();

// 10分間隔でランキングを更新（NGフィルタリング付き）
crons.interval(
  "update all rankings with NG",
  { minutes: 10 },
  api.updateRankingWithNG.updateAllRankingsWithNG
);

export default crons;