// Type definitions for Convex
// These will be generated by Convex CLI in production

declare module "convex/server" {
  export function defineSchema(schema: any): any;
  export function defineTable(table: any): any;
  export function mutation(config: any): any;
  export function action(config: any): any;
  export const cronJobs: () => any;
}

declare module "convex/values" {
  export const v: {
    string: () => any;
    number: () => any;
    boolean: () => any;
    array: (item: any) => any;
    object: (schema: any) => any;
    union: (...args: any[]) => any;
    literal: (value: any) => any;
    optional: (value: any) => any;
    any: () => any;
  };
}

declare module "./_generated/api" {
  export const api: {
    updateRanking: {
      updateCronStatus: string;
      updateAllRankings: string;
    };
    cloudflareKVWriter: {
      writeToCloudflareKV: string;
    };
  };
}