// Generated by Wrangler by running `wrangler types`

interface Env {
	RANKING_DATA: KVNamespace;
	MAINTENANCE_FLAGS: KVNamespace;
	VERCEL_DEPLOYMENT_URL: string;
	WORKER_AUTH_KEY: string;
	R2_BUCKET: R2Bucket;
	WORKER_BLUE: Fetcher;
	WORKER_GREEN: Fetcher;
}
