name = "nico-ranking"
compatibility_date = "2024-01-09"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.next"

[[kv_namespaces]]
binding = "RANKING_KV"
id = "your_namespace_id_here"

[env.production]
vars = { NODE_ENV = "production" }