# =============================================================================
# Cloudflare Workers Configuration - API Gateway & Cron Jobs
# =============================================================================
# IMPORTANT: This project uses a hybrid deployment strategy:
# - Main Next.js application: Deployed to Vercel
# - API Gateway & Rate Limiting: Deployed to Cloudflare Workers
# - Cron Jobs: Cloudflare Workers Cron for ranking updates
# - Storage: Cloudflare KV
# 
# This wrangler.toml configures both API Gateway and Cron Workers.
# The main application should NOT be deployed to Cloudflare Pages.
# =============================================================================

name = "nico-ranking-api-gateway"
main = "workers/api-gateway-simple.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Environment variables
[vars]
NEXT_APP_URL = "https://nico-ranking-custom-yjsns-projects.vercel.app"
USE_PREVIEW = "false"  # "true" でプレビュー環境を使用
# WORKER_AUTH_KEY should be set as a secret using: wrangler secret put WORKER_AUTH_KEY

# Account settings
account_id = "5984977746a3dfcd71415bed5c324eb1"

# KV Namespaces
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c49751cf8c27464aac68cf030b9e0713"
preview_id = "c49751cf8c27464aac68cf030b9e0713"

[[kv_namespaces]]
binding = "RANKING_KV"
id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"
preview_id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"

# Routes
[[routes]]
pattern = "nico-rank.com/*"
zone_name = "nico-rank.com"

[[routes]]
pattern = "www.nico-rank.com/*"
zone_name = "nico-rank.com"

# Development settings
[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"

# Build settings
[build]
command = ""

# Performance settings
# [limits]
# cpu_ms = 50  # CPU limits require paid plan
# memory_mb = 128

# Compatibility settings
# compatibility_flags = ["nodejs_compat"]

# Preview environment for current branch
[env.preview]
name = "nico-ranking-api-gateway-preview"

[env.preview.vars]
NEXT_APP_URL = "https://nico-ranking-custom-yjsns-projects.vercel.app"
# WORKER_AUTH_KEY should be set as a secret using: wrangler secret put WORKER_AUTH_KEY

[[env.preview.routes]]
pattern = "preview.nico-rank.com/*"
zone_name = "nico-rank.com"

[[env.preview.kv_namespaces]]
binding = "RATE_LIMIT"
id = "c49751cf8c27464aac68cf030b9e0713"

[[env.preview.kv_namespaces]]
binding = "RANKING_KV"
id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"

# =============================================================================
# Cron Worker Configuration
# =============================================================================

# Cron Worker for fetching ranking data
[env.cron]
name = "nico-ranking-cron"
main = "workers/cron-ranking-fetcher.ts"

# Cron triggers - 10分ごとに実行
[[env.cron.triggers]]
crons = ["*/10 * * * *"]

# Queue binding for async task processing
[[env.cron.queues]]
binding = "RANKING_QUEUE"
queue = "ranking-tasks"

# Durable Objects for coordination
[[env.cron.durable_objects]]
binding = "RANKING_PROCESSOR"
class_name = "RankingProcessor"
script_name = "workers/ranking-processor-durable-object"

# Durable Object migrations
[[env.cron.migrations]]
tag = "v1"
new_classes = ["RankingProcessor"]

# KV namespaces for cron worker
[[env.cron.kv_namespaces]]
binding = "RANKING_KV"
id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"

[[env.cron.kv_namespaces]]
binding = "RATE_LIMIT"
id = "c49751cf8c27464aac68cf030b9e0713"

# Environment variables for cron
[env.cron.vars]
# CRON_SECRET should be set as a secret
# GITHUB_TOKEN for fallback notifications (optional)