name = "nico-ranking-api-gateway"
main = "workers/api-gateway-simple.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Environment variables
[vars]
NEXT_APP_URL = "https://nico-ranking-custom-yjsns-projects.vercel.app"

# Account settings
account_id = "5984977746a3dfcd71415bed5c324eb1"

# KV Namespaces
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c49751cf8c27464aac68cf030b9e0713"
preview_id = "c49751cf8c27464aac68cf030b9e0713"

[[kv_namespaces]]
binding = "RANKING_DATA"
id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"
preview_id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"

# Routes
[[routes]]
pattern = "nico-rank.com/*"
zone_name = "nico-rank.com"

[[routes]]
pattern = "www.nico-rank.com/*"
zone_name = "nico-rank.com"

# Development settings
[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"

# Build settings
[build]
command = ""

# Performance settings
# [limits]
# cpu_ms = 50  # CPU limits require paid plan
# memory_mb = 128

# Compatibility settings
compatibility_flags = ["nodejs_compat"]