name = "nico-ranking-api-gateway-r2-v2"
main = "workers/api-gateway-r2-v2.ts"
compatibility_date = "2024-10-01"

[env.production]
vars = { ENVIRONMENT = "production" }
workers_dev = false

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "nico-ranking"

[placement]
mode = "smart"