name = "nico-ranking-api-gateway"
main = "workers/api-gateway-dynamic-cache.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "RANKING_DATA"
id = "80f4535c379b4e8cb89ce6dbdb7d2dc9"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "nico-ranking"

[vars]
VERCEL_DEPLOYMENT_URL = "https://nico-ranking-custom-yjsns-projects.vercel.app"

[[routes]]
pattern = "nico-rank.com/*"
zone_name = "nico-rank.com"