name = "nico-ranking-api-gateway"
main = "workers/api-gateway.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Environment variables
[vars]
NEXT_APP_URL = "https://nico-ranking.vercel.app"

# Account settings
account_id = "your_account_id"

# KV Namespaces (実際のIDに置き換えてください)
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "your_rate_limit_namespace_id"
preview_id = "your_rate_limit_preview_id"

[[kv_namespaces]]
binding = "RANKING_DATA"
id = "your_ranking_data_namespace_id"
preview_id = "your_ranking_data_preview_id"

# Routes (ドメイン設定後に有効化)
# [[routes]]
# pattern = "yourdomain.com/*"
# zone_name = "yourdomain.com"

# Development settings
[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"

# Build settings
[build]
command = "npm install && npm run build"
watch_paths = ["workers/**/*.ts"]

# Performance settings
[limits]
cpu_ms = 50
memory_mb = 128

# Compatibility settings
[compatibility_flags]
nodejs_compat = true