/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as crons from "../crons.js";
import type * as ranking from "../ranking.js";
import type * as schema from "../schema.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  ranking: typeof ranking;
  schema: typeof schema;
}>;

export type FilterApi<T, U> = any;

export type FunctionReference<Type, Visibility> = any;

// Temporary exports for development
export const internal = {
  ranking: {
    updateAllRankings: {} as any,
    cleanupExpiredTagCache: {} as any,
    saveSnapshot: {} as any,
    saveTagRankingCache: {} as any,
  }
} as any;

export const api = {} as any;