/* eslint-disable */
/**
 * Generated `server` utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

// Temporary type definitions for development
export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;

export function query(config: any): any {
  return config;
}

export function mutation(config: any): any {
  return config;
}

export function action(config: any): any {
  return config;
}

export function internalQuery(config: any): any {
  return config;
}

export function internalMutation(config: any): any {
  return config;
}

export function internalAction(config: any): any {
  return config;
}

export const v = {
  string: () => ({} as any),
  number: () => ({} as any),
  boolean: () => ({} as any),
  array: (schema: any) => ({} as any),
  object: (schema: any) => ({} as any),
  optional: (schema: any) => ({} as any),
  any: () => ({} as any),
};