name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies with retry
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          for i in {1..3}; do
            if npm ci; then
              break
            else
              echo "npm ci failed (attempt $i/3), retrying in 30 seconds..."
              sleep 30
            fi
          done

      - name: Type check
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run unit and integration tests with coverage
        run: npm run test:coverage

      - name: Check coverage thresholds
        run: npx vitest --coverage --run

      # Codecov upload disabled - requires token configuration
      # - name: Upload coverage reports
      #   uses: codecov/codecov-action@v5
      #   with:
      #     file: ./coverage/coverage-final.json
      #     fail_ci_if_error: true

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # E2E tests disabled - requires KV environment variables
      # - name: Run E2E tests
      #   run: npm run test:e2e
      #   env:
      #     PLAYWRIGHT_BASE_URL: http://localhost:3000

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies with retry
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          for i in {1..3}; do
            if npm ci; then
              break
            else
              echo "npm ci failed (attempt $i/3), retrying in 30 seconds..."
              sleep 30
            fi
          done

      - name: Build application
        run: npm run build

      - name: Check bundle size
        run: |
          npm install -g @next/bundle-analyzer
          ANALYZE=true npm run build

  security:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies with retry
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          for i in {1..3}; do
            if npm ci; then
              break
            else
              echo "npm ci failed (attempt $i/3), retrying in 30 seconds..."
              sleep 30
            fi
          done
      
      - name: Run security audit
        run: npm audit --audit-level=critical || true