name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the workflow if high or critical vulnerabilities are found
          fail-on-severity: high
          
          # Block PRs that introduce vulnerable dependencies
          vulnerability-check: true
          
          # Check for license issues
          license-check: true
          
          # Allowed licenses (common open source licenses)
          allow-licenses: |
            MIT
            Apache-2.0
            BSD-2-Clause
            BSD-3-Clause
            ISC
            0BSD
            CC0-1.0
            CC-BY-3.0
            CC-BY-4.0
            Unlicense