name: Update Nico Ranking Data

on:
  schedule:
    # Run every 30 minutes
    - cron: '0,30 * * * *'
  workflow_dispatch: # Allow manual trigger
  
jobs:
  update-ranking:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update ranking data in KV
      env:
        KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
        KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
      run: npm run update:kv
    
    - name: Check update status
      run: |
        if [ $? -eq 0 ]; then
          echo "Successfully updated all ranking data"
        else
          echo "Failed to update some ranking data"
          exit 1
        fi